# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: klakegg/hugo:asciidoctor

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
