# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: 
  name: klakegg/hugo:asciidoctor
  entrypoint: [""]

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo -d _public
  - mkdir public
  - mv _public/* public
  artifacts:
    paths:
    - public
  only:
  - master
