baseurl = "http://www.norwegianlanguagelearning.no"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Norwegian Language Learning"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  #subtitle = "NLL on the Web"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.png"
  dateFormat = "2006-01-02"
  commit = false
  rss = false
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[Author]
  name = "NLL contributors"
  #email = "youremail@domain.com"
  gitlab = "NorwegianLanguageLearning"


[[menu.main]]
	name = "Home"
	url = ""
	weight = 1

[[menu.main]]
	name = "Lessons"
	url = "categories/sunday-lessons/"
	weight = 2

[[menu.main]]
	name = "About"
	url = "page/about/"
	weight = 3


[[menu.main]]
	name = "More information"
	identifier = "info"
	url = "page/info"
	weight = 4

[[menu.main]]
	parent = "info"
	name = "Rules"
	url = "page/rules"
	weight = 1

[[menu.main]]
	parent = "info"
	name = "Channel explanations"
	url = "page/channels"
	weight = 2

[[menu.main]]
	parent = "info"
	name = "Heimdallr"
	url = "page/heimdallr"
	weight = 3

#[[menu.main]]
#	name = "Tags"
#	url = "tags"
#	weight = 3
