backend:
  name: github
  repo: NLLCommunity/nllcommunity.github.io

media_folder: /public/media
public_folder: /media

collections:
  - name: posts
    label: Posts
    folder: content/post
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Subtitle"
        name: "subtitle"
        widget: "string"

      - label: "Author"
        name: "author"
        widget: "string"

      - label: "Date"
        name: "date"
        widget: "datetime"

      - label: "Categories"
        name: "categories"
        widget: "list"

      - label: "Body"
        name: "body"
        widget: "richtext"
