---
title: "Norwegian Slang, Insults, and Swears"
date: "2019-01-16"
author: "Dan"
categories:
  - Sunday lessons
---
When learning a new language, it is helpful to learn some of the slang.
This will help improve your listening skills, whether you’re having a
conversation with a Norwegian or just watching TV or a film in
Norwegian, etc. It will also help you sound a bit more natural when you
speak the language.

This lesson will cover slang words, insults, and swear words (I know
they can overlap).
<!--more-->

== Salutations

[cols=",,,",]
|===
|_Heisann. +
Hallo. +
Halla. +
Halloen._ |Hi. |_Alt bra med deg?_ |Everything good with you?

|_Mårn._ |Morning. |_Hva skjer? +
Skjer ’a? +
Skjer?_ |What’s up? / What’s happening?

|_Hva har du drevet med?_ |What have you been up to? |_Er du med? +
Er du gira?_ |Are you up for it? / Are you in?

|_Ha det (bra)._ |Bye |_Ha det moro!_ |Have fun! / Enjoy!

|_Jeg drar._ |I’m off. (I’m leaving). |_Hils_ |Regards (e.g. Give my
regards to them).
|===

“Er du med” and “Er du gira” are used when you want to ask someone if
they want to hang out and / or go do something?

Ex: Jeg vil spille D&D. Er du med? (Er du gira?)

I want to play D&D. Are you up for it? / Are you in?

“Hils” is something you say to someone when you want them to say hi from
you

Ex: Person 1: Jeg skal besøke Lucas.

Person 2: Okay, hils.

Person 1: I’m going to visit Lucas.

Person 2: Okay, give him my regards / say hi to him for me.

== Expressing that something is great

Sometimes we want to express our appreciation or our enthusiasm for
something (or someone) that we think is wonderful.

[cols=",,,,",]
|===
| |*Slang* |*Meaning* |*Example* |*English*

|*1.* |Fantastisk |_Fantastic_ |Filmen var fantastisk! |_The film was
fantastic!_

.2+|*2.* .2+|Alle tiders .2+|_Best of times_ |Det var en alle tiders tur. |_It
was best trip of all times._

|Han var en alle tiders skuespiller. |_He was the best actor of
all times._

|*3.* |Lættis |_Funny_ |Showet er så lættis |_The show is so funny._

|*4.* |Kult / Schpaa / Fett |_Cool_ a|
Person 1: Jeg fikk det nye videospillet.

Person 2: Kult! / Schpaa! / Fett!

a|
_Person 1: I got the new video game!_

_Person 2: Cool!_

|*5.* |Dritkult |_Really cool_ a|
Person 1: Jeg fikk autografen hans!

Person 2: Dritkult!

a|
_Person 1: I got his autograph!_

_Person 2: That’s really cool!_

|*6.* |Adda |_So cool!_ a|
Person 1: Jeg har billetter til konserten!

Person 2: Adda!

|_Person 1: I have tickets to the concert! +
Person 2: So cool!_

|*7.* |Schmø |_Fine; nice_ |Det var schmø. |_It was fine / nice._

|*8.* |Sykt (bra) |_Very good_ |Det trikset var helt sykt! |_That trick
was totally sick / awesome!_

|*9.* |Knallbra |_Awesome_ |Festen var knallbra! |_The party was
awesome!_
|===

== Expressing that something is bad

Of course, there are times when we really want to express our
disappointment or disgust in something (or someone).

[cols=",,,,",]
|===
| |*Slang* |*Meaning* |*Example* |*English*

.2+|*1.* .2+|Klein .2+|_To be hungover or embarrassed; or to feel awkward during
a conversation_ |Da han snakket med meg, var det kleint. |_When he was
talking with me, I was awkward._

|Da jeg våknet, var jeg klein. |_When I woke up, I was hungover._

|*2.* |Døll |_Dull, boring_ |Festen er så døll. |_The party is so
boring._

|*3.* |Det var litt på kanten. |_Something that crossed the line._ |Hans
vitsen var litt på kanten. |_His joke crossed the line._

|*4.* |God s |_Short for “god stemning” (meaning having a good time) but
used sarcastically (i.e. not having a good time)._ a|
Person 1: Har du det gøy på turen?

Person 2: Med søsknene mine som irriterer meg? Ja, god s.

a|
_Person 1: Are you having fun on the trip?_

_Person 2: With my siblings annoying me? Yeah, good times._

|*5.* |Æsj! |_Ew!_ |Æsj! Orm er ekkelt! |_Ew! Worms are disgusting!_

|*6.* |Kjipt |_Sucks; unfortunate_ a|
Person 1: Jeg mislyktes på eksamenen.

Person 2: Det er kjipt.

a|
_Person 1: I failed the exam._

_Person 2: That sucks._

|*7.* |Fysj |_Used to express disgust; gross_ a|
Person 1: Han vasket ikke hendene sine etter at han hadde brukt
toalettet.

Person 2: Fysj!

a|
_Person 1: He didn't wash his hands after he used the toilet._

_Person 2: Gross!_

|===

== Intensifiers

Sometimes just using an adjective doesn’t fully describe how we feel
about something, so Norwegians will use intensifiers to emphasize the
adjectives.

[cols=",,,",]
|===
| |*Intensifier* |*Example* |*English*

|*1.* |Kjempe |Jeg var kjempeglad da jeg møtte Mads. |_I was extremely
happy when I met Mads._

|*2.* |Veldig |Maten smaker veldig godt! |_The food tastes really good!_

|*3.* |Super |Person 1: Jeg fikk jobben! +
Person 2: Det er super knallbra! a|
_Person 1: I got the job!_

_Person 2: That is super awesome!_

|*4.* |Mega |Han er megadeilig i den nye filmen! |_He looks extremely
hot in the new film!_

|*5.* |Ekstremt |Person 1: Han ble sparket fra jobben sin. +
Person 2: Det var ekstremt kjipt. |_Person 1: He was fired from his
job. +
Person 2: That extremely sucks._

|*6.* |Utrolig |Der er utrolig mange kvinner her. |_There are a ton of
women here._
|===

*[.underline]#Note:#* “Super” can be used on its own to mean “great” or
that something is “super” as in English.

Ex: Person 1: Sønnen min har vunnet konkurransen!

Person 2: Det er supert!

Person 1: My son has won the contest!

Person 2: That’s super!

== Random Slang & Phrases

Most of the things in this table have a negative connotation while
others are more neutral. There are also a few phrases / idioms that,
while not technically slang, they are still odd (and make no sense when
directly translated), so I thought I would include them. This is not an
exhaustive list.

[cols=",,,,",]
|===
| |*Slang* |*Meaning* |*Example* |*English*

|*1.* |Serr |_Short for “seriøst,” which means “seriously”_ a|
Person 1: Han var utro mot kjæresten sin.

Person 2: Serr?!

a|
_Person 1: He cheated on his partner._

_Person 2: Seriously?!_

|*2.* |Kødder du? |_Are you kidding?_ a|
Person 1: Vi fikk oss en katt til.

Person 2: Kødder du?

a|
_Person 1: We got another cat._

_Person 2: Are you kidding me?_

|*3.* |Krangle |_Arguing / Quarreling_ |Erik og Lukas krangler igjen.
|_Erik and Lukas are quarreling again._

|*4.* |Å hooke |_Hooking up (kissing; making out)_ |De hooka på festen i
går. |_They were making out at the party yesterday._

|*5.* |Å shippe |_To ship two people (i.e. you want them in a
relationship)_ |Alle vet at jeg shipper Hannibal og Will. |_Everyone
knows I ship Hannibal and Will._

|*6.* |Å tæsje / bøffe |_To steal_ |Tæsja / Bøffa du det? |_Did you
steal it?_

.2+|*7.* .2+|Drøy(t) .2+|_Too much information; or have a tendency to engage in
TMI or take things too far._ |Du er drøy. |_You are giving too much
info._

|Det var drøyt. |_That was too much info._

|*8.* |Brisen |_Tipsy_ |Hun var brisen etter festen. |_She was tipsy
after the party._

|*9.* |Null komma nix |_Something that was done quickly; it was done in
no time._ |Jeg gikk banken og var ferdig på null komma nix. |_I went to
the bank and was done in no time._

|*10.* a|
Hold kjeft!

Hold smella!

|_Shut up!_ |Hold kjeft! Jeg kan ikke høre filmen! |_Shut up! I cannot
hear the movie!_

|*11.* |Heldiggris (en) |_Someone who is lucky_ a|
Person 1: Jeg vant noen kunstverk.

Person 2: Heldiggris!

|_Person 1: I won some artwork. +
Person 2: You’re lucky!_

|*12.* |Slikk og ingenting |_Nothing; very small amount_ |Eieren trodde
den var verdiløs, så jeg fikk bilen for en slikk og ingenting. |_The
owner thought it was worthless so i got the car for (almost) nothing._

|*13.* |Alkis (en) |_Alcoholic_ |Broren din er en alkis. |_Your brother
is an alcoholic._

|*14.* |Det går i ett kjør. |_Everything happens really quickly, all at
once, but kind of chaotic._ |Vi var så opptatt på jobb i dag. Det gikk i
ett kjør. |_We were so busy at work today. It went by really fast._

|*15.* |Å drite seg ut |_To make a fool of oneself_ |Han dret seg ut da
han var full. |_He was making a fool of himself when he was drunk._

|*16.* |Laken |_1000 kroner note_ |Du skylder meg ti laken. |_You owe me
ten grand. (10000)_

|*17.* |Snut (en ) / Purk (en) |_Police_ |Han ringte snuten / purken!
|_He called the police!_

|*18.* |Sigg (en) |_Cigarette_ |Kan jeg få en sigg? |_Can I get a
cigarette?_

|*19.* |Hæ? |_Huh? What?_ |Person 1: Hvor er biblioteket? +
Person 2: Hæ? |_Person 1: Where is the library? +
Person 2: Huh?_

|*20.* |Drikkekamerat (en) |_Drinking buddy_ |Tobias er drikkekameraten
min. |_Tobias is my drinking buddy._

|*21.* |Døddrukken |_Fall-over-drunk_ |Hun var døddrukken i går kveld.
|_She was fall-over-drunk last night._

|*22.* |Ølbriller |_Beer glasses / goggles_ |Du har ølbriller på. Han er
egentlig ikke kjekk. |_You have beer goggles on. He is not really
handsome._

|*23.* |Skækk |_High / wasted (also: an answer for when someone asks
about something obvious)._ |Er du skækk eller? |_Are you high?_

|*24.* |Snik |_To be a sneaky person_ |Sønnen hennes var en snik. |_Her
son was being a sneaky (person)._

|*25.* |Mac(c)ern |_McDonald’s_ |Jeg har mat fra Maccern hvis du er
sulten. |_I have food from McDonald’s, if you’re hungry._

|*26.* |Legg (en) |_ID card_ |Jeg finner ikke leggen min! |_I can’t find
my ID Card!_

|*27.* |Flæ |_Drunk_ |Har du vært på flæ? |_Have you been drunk?_

|*28.* |DLEG |_Short for “du lever én gang.” YOLO_ |Person 1: Skal du
hoppe i strikk?! +
Person 2: Jepp. DLEG. a|
_Person 1: You’re going to bungee jump?!_

_Person 2: Yep. YOLO._

|*29.* |Ins |_Abbreviation (text) for “ikke noe spesielt.” (Nothing
special)._ |Person 1: Hva skal du på bursdagen din? +
Person 2: Ins. |_Person 1: What are you doing on your birthday? +
Person 2: Nothing special_

|*30.* |Gerro |_Smoke_ |Jeg hater menn som gerro. |_I hate men that
smoke._

|*31.* |Å chille |_To relax_ |Jeg chiller denne helgen. |_I’m relaxing
this weekend._

|*32.* |Sofagris (en) |_Couch potato_ |Broren min er en sofagris. |_My
brother is a couch potato._

|*33.* |Snørrbrems (en) |_Mustache_ |Jeg liker snørrbremsen hans. |_I
like his mustache._

|*34.* |Helt texas |_Completely crazy (chaotic)_ |Jeg har vært på
shopping til jul på 23. desember og det var helt texas i butikken. |_I
went shopping for Christmas on December 23rd and it was completely crazy
in the store._

.2+|*35.* .2+|Skjerp deg! .2+a|
_Straighten up!_

_Get yourself together._

|(Barn oppfører seg dårlig) +
Mor: Skjerp deg! |_(Child behaves badly) +
Mother: Straighten up!_

|(Venn gjør noe galt) +
Du: Skjerp deg! |_(Friend does something wrong) +
You: Straighten up!_

|*36.* |Bombe |_Surprise (used sarcastically)_ |Person 1: Han var full i
går. +
Person 2: Bombe. |_Person 1: He was drunk yesterday. +
Person 2: Surprise._

|*37.* a|
Vors (et)

_(pronounced fors)_

|_Pre-party (get together before going out for drinks)_ |Vi møtes for et
vors i huset hans. |_We’re meeting for a pre-party at his house._

|*38.* |Huttiheita |_Middle of nowhere_ |Hun bor i huttiheita. |_She
lives in the middle of nowhere._

|*39.* |Uff! |_Ugh! (Expresses annoyance; frustration; exasperation)_
|Uff! Må jeg gjøre alt arbeidet? |_Ugh! Must I do all the work?_

|*40.* |Kis (en) / Fyr (en) |_Dude_ |Hva skjer, kis / fyr? |_What’s up,
dude?_

|*41.* |Pell deg vekk |_Get lost / leave._ |Pell deg vekk herfra, din
gris! |_Get away from here you pig!_
|===

*[.underline]#Note:#* Some of these words are more common in different
areas, for example, slang that is considered “kebab-norsk” tends to be
more common in Oslo and the surrounding areas.

== “Contractions”

In Norwegian, technically there are no actual contractions of words.
However, in spoken Norwegian, it is quite common. These are just a few
examples, and are not a written standard and are *only* used in spoken
Norwegian.

[cols=",,,",]
|===
|*Contraction* |*Word 1* |*Word 2* |*Meaning*
|Kan’ke |Kan .9+|Ikke |Cannot
|Må’kke |Må |Must not
|Ska’kke |Skal |Shall not
|Vi’kke |Vil |Will not
|E’kke |Er |Is not
|Dra’kke |Drar |Not leaving
|Gå’kke |Går |Not going
|Va’kke |Var |Was not
|Ha’kke |Har |Have not
|===

== Insults & Swears

It is important to note that, in Norwegian culture, swearing is pretty
commonplace. In English, dropping an F-bomb would seem inappropriate in
many settings (and many feel it should not be uttered by children),
however in Norway, no such taboos really exist. It is common, for
example, to hear children use swear words and not unheard of to see them
in newspaper headings.

[cols=",,,,",]
|===
| |*Insult / Swear* |*Meaning* |*Example* |*English*

.2+|*1.* .2+|Dust (en) .2+|_Idiot; jerk (can also be used flirtatiously with a
partner)_ |Han var en dust på festen. |_He was a jerk at the party._

|Kjæresten fniser: Du er en dust. |_Girlfriend giggles: You’re an
idiot._

|*2.* |Lø |_Boring or lame_ |Foreldrene mine er så lø. |_My parents are
so boring._

|*3.* |Gjøk (en) / Fjott (en) |_Idiot; someone stupid_ |Uff! Onkelen min
er en gjøk / fjott. |_Ugh! My uncle is an idiot!_

|*4.* |Dum |_Stupid; dumb_ |Sjefen min er dum! |_My boss is stupid!_

|*5.* |Sutrekopp |_Whiner, crybaby_ |Presidenten er en sutrekopp |_The
president is a whiner._

.2+|*6.* .2+|Teit [adj.] / Teiting (en) [n.] .2+|_Someone who is stupid or
annoying_ |Lillebroren min er en teiting. |_My little brother is
annoying._

|Ikke vær teit. |_Don’t be stupid._

|*7.* |Kronidiot (en) |_Biggest idiot_ |Presidenten er en kronidiot!
|_The president is the biggest idiot!_

|*8.* |Slaur (en) |_Lazy person (dialect, used more in western Norway)_
|Kollegaen min er en slaur. |_My coworker is lazy._

|*9.* |Mehe (et) |_Someone who follows others; doesn’t think for
themself._ |Han gjør akkurat det han blir fortalt. For et mehe. |_He
just does whatever he is told. What a pushover / doormat._

|*10.* |Feiging (en) |_Coward_ |Ikke vær en feiging; se denne filmen med
meg. |_Don’t be a coward; watch this film with me._

|*11.* |Urokråke (ei) |_Troublemaker_ |Jeg liker urokråker. |_I like
troublemakers._

|*12.* |Klossmajor (en) |_Klutz; someone who is clumsy_ |Jeg er en sånn
en klossmajor. Jeg snubler over alt. |_I am such a klutz. I trip over
everything._

|*13.* |Vattnisse (en) |_Scaredy cat; wimp_ |Broren min spiller ikke
skrekkspill fordi han er en vattnisse. |_My brother doesn’t play horror
games because he is a wimp._

|*14.* |Svin (et) |_Pig_ |Presidenten er et svin! |_The president is a
pig!_

|*15.* |Bæsj |_Poop_ |Det er bæsj. |_It is poop._

|*16.* |Helsike |_Heck_ |Hva i helsike skjedde? |_What the heck
happened?_

.2+|*17.* .2+|Helvete .2+|_Hell_ |Hva i helvete skjedde? |_What the hell
happened?_

|Dra til helvete! |_Go to hell!_

|*18.* |Herregud |_Oh my God_ |Herregud! Hva gjorde du? |_Oh my God!
What did you do?_

|*19.* |Søren! +
Dæven! +
Dæsken! +
Pokker! |_Damn!_ |Søren! Jeg gledet meg til den filmen. |_Damn! I was
looking forward to the film._

|*20.* |Rumpehull (et) |_Butthole_ |Han kan være et rumpehull noen
ganger. |_He can be a butthole sometimes._

.2+|*21.* .2+|Dritt / Skitt .2+|_Shit_ |Jeg er lei av dritten din! |_I’m tired of
your shit!_

|Vi hadde drittvær i går. |_We had shit weather yesterday._

|*22.* |Drittunge (en) / Snørrunge (en) |_Brat_ |Uff! Søsknene dine er
noen drittunger / snørrunger! |_Ugh! Your siblings are such brats!_

|*23.* |Drittsekk (en) |_Scumbag / shitbag_ |Politikeren er en
drittsekk! |_The politician is a scumbag!_

|*24.* |Dritthode (et) |_Shithead_ |Eks-kjæresten min er et dritthode.
|_My ex-boyfriend is a shithead._

|*25.* |Ræv (en) / Rass (en) |_Ass_ |Kyss meg i ræva! |_Kiss my ass!_

|*26.* |Rævhøl (et) / Rasshøl (et) |_Asshole_ |Det fulle rævhullet
startet kampen. |_The drunk asshole started the fight._

.2+|*27.* .2+|Jævel / Jævla .2+|_Fucker / Fucking_ |Det er jævlig dyrt! |_It is
fucking expensive!_

|Du er en jævla drittsekk. |_You’re a fucking shitbag._

.2+|*28.* .2+a|
Faen (ta deg)

_(Pronounced fa-an)_

|_Fuck_ |Det faen meg ikke sant! |_That isn’t fucking true!_

|_Fuck you_ |Jeg kan ikke tro at du løy! Faen ta deg! |_I can’t
believe you lied! Fuck you!_

|*29.* |Fy faen |_For fuck’s sake_ |Fy faen! Nå starter ikke bilen!
|_For fuck’s sake! Now the car won’t start!_

.2+|*30.* .2+|Satan / Satans .2+|_Fuck (used as an exclamation or to emphasize)_
|Satan! Jeg har glemt bankkortet mitt! |_Fuck! I forgot my debit card._

|Uff! Satans drittunger! |_Ugh! Fucking brats!_

|*31.* |Føkka |_Fucked up_ a|
Person 1: Han ranet banken.

Person 2: Det er føkka.

|_Person 1: He robbed the bank. +
Person 2: That’s fucked up._

|*32.* |Forpulte |_“Fucked out” from å pule = to fuck_ |Din forpulte
drittsekk |_You fucking piece of shit_
|===

In Norwegian, when calling someone a name, it is typical for it to be
said with “din / ditt” instead of “du.”

Ex: Din idiot! Ditt svin!

You idiot! You pig!

*_{asterisk}{asterisk}If the lesson was beneficial, please consider
https://ko-fi.com/R5R0CTBN[[.underline]#buying me a virtual coffee.#] Thanks.{asterisk}{asterisk}_*

References:

https://ndla.no/nb/node/54049?fag=6118[[.underline]#Dialekter, sjargong, slang og lokalkunnskap#]

http://streettalksavvy.com/norwegian-slang[[.underline]#Norwegian Slang#]

https://youtu.be/11CkJC2civo[[.underline]#Norwegian Slang: Joining Verbs with Not (YouTube)#]

https://www.scandikitchen.co.uk/13-scandinavian-insults[[.underline]#13 Useful Scandinavian Insults#]

https://youtu.be/toED64QA7kg[[.underline]#Norwegian Slang - Part 1 - phrases, words and sentences! (YouTube)#]

https://youtu.be/LZInGgEDfGs[[.underline]#Norwegian Slang - Part 2 - Phrases and Comparisons (YouTube)#]

https://youtu.be/nm6SuGbgMfk[[.underline]#Norwegian Slang - Part 3 - Sayings (YouTube)#]

https://snl.no/slang[[.underline]#Store Norsk Leksjon: Slang#]

https://youtu.be/US93XxGINqQ[[.underline]#Norwegian Slang! // SKAM (YouTube)#]

https://youtu.be/DHg1fOylZvQ[[.underline]#Norwegian Slang (YouTube)#]

https://www.duo.uio.no/bitstream/handle/10852/49985/FERDIG.pdf?sequence=1[[.underline]#Slang i Norsk (pdf)#]

https://youtu.be/K1k9DrUFI0k[[.underline]#Sunny: Norwegian Slang (YouTube)#]

https://www.vi.no/familie/alo-sier-ungdommen-men-hva-betyr-det/69833751[[.underline]#Nye Norske Ord#]

https://blogs.transparent.com/norwegian/curse-words-in-norwegian[[.underline]#Curse words in Norwegian#]

https://youtu.be/DIl4QrGy7vs[[.underline]#Typisk Norsk S01E07 Slang og sjargong klipp 1 (YouTube)#]

https://politiken.dk/kultur/filmogtv/art5638633/Skam-er-tilbage-Her-er-25-norske-ord-du-ikke-fatter[[.underline]#Skam er tilbage: Her er 25 norske ord, du ikke fatter#]

https://youtu.be/pT-X9WXTS-w[[.underline]#Sunny: Norwegian Swear Words (YouTube)#]

https://matadornetwork.com/notebook/10-untranslatable-norwegian-terms[[.underline]#10 untranslatable Norwegian terms#]

http://pardonmynorwegian.tumblr.com/post/50108060062/so-a-while-back-i-asked-for-your-help-with-some[[.underline]#Norwegian Slang, Y'all#]

http://pardonmynorwegian.tumblr.com/post/44072566386/weve-now-reached-a-critical-moment-in-pardon-my[[.underline]#Pardon my Norwegian: Swear Words#]

https://norskbloggen.no/ritual-meeting-greeting-part-1[[.underline]#The Norwegian Rituals of Meeting and Greeting#]

https://youtu.be/aRDOtw80oSw[[.underline]#Norwegian Swear Words (YouTube)#]

https://toppnorsk.com/2017/02/07/banneord[[.underline]#Banneord#]

https://forskning.no/kultur/norges-forste-banneordbok-slik-banner-vi/1125663[[.underline]#Norges første banneordbok: Slik banner vi#]

https://www.aftenbladet.no/forsta/i/0op7M/Slik-banner-du-pa-stavangersk[[.underline]#Slik banner du på stavangersk#]

*[.underline]#Exercise:# We will pair up; write a dialogue with your
partner.*
