---
title: "To do, to play"
date: "2020-06-07"
author: "Dan"
categories:
  - Sunday lessons
---
When learning Norwegian, one will come across verbs that can sometimes
be difficult for new learners to understand how and when they are used.
Often in these cases, the verbs might translate into the same English
word, but cannot be used interchangeably in Norwegian. Let’s look at
some examples.
<!--more-->

== Grammar Review

=== Sentence structure

While most Norwegian sentences use the subject-verb-object (SVO) word
order, like English does, Norwegian does have the V2 (verb second) rule.
If an adverbial phrase or subordinate clause is at the front of the
sentence, the subject and the verb have to switch places (this is called
“inversion”) so that the verb stays in the second position.

[cols=",,",]
|===
| |*Eksempel* |*English*

.2+|*SVO* |Marianne vasket hunden i går. |_Marianne washed the dog
yesterday._

|Bjørn møtte vennen sin da han besøkte Oslo. |_Bjørn met his friend
when he visited Oslo._

.2+|*V2* |I går vasket Marianne hunden. |_Yesterday, Marianne washed the
dog._

|Da Bjørn besøkte Oslo, møtte han vennen sin. |_When Bjørn visited
Oslo, he met his friend._
|===

If a sentence has more than one verb, the second verb will be in a
nonfinite form (e.g. å finne). If the sentence has inversion, then the
subject will come between the finite (i.e. conjugated) verb and the
nonfinite verb.

[cols=",,",]
|===
| |*Eksempel* |*English*

.2+|*SVO* |Markus prøvde å tegne en dinosaur i går. |_Markus tried to draw
a dinosaur yesterday._

|Emma pleide å løpe 5km hver dag, da hun var yngre. |_Emma used to run
5 km every day, when she was younger._

.2+|*V2* |I går prøvde Markus å tegne en dinosaur. |_Yesterday, Markus
tried to draw a dinosaur._

|Da Emma var yngre, pleide hun å løpe 5km hver dag. |_When Emma was
younger, she used to run 5 km every day._
|===

=== Verb Conjugation

Conjugating the present tense of verbs in Norwegian is fairly simple.
Most present tense verbs just add an -r to the end of the infinitive and
drop the infinitive marker (å).

[cols=",,,,,",]
|===
|*Infinitive* |*Present* |*English* |*Infinitive* |*Present* |*English*

|Å besøke |besøker |_Visits / Visiting_ |Å svømme |svømmer |_Swims /
Swimming_

|Å kjøre |kjører |_Drives / Driving_ |Å begynne |begynner |_Begins /
beginning_
|===

Past tense conjugation is a bit more difficult, however there are some
guidelines (but keep in mind there are exceptions).

[arabic]
. If the verb ends with a double consonant, consonant cluster, or voiced
plosive (b / d), past tense will end in -et.
. If the verb ends in a single consonant (except v / b / d), past tense
ends in -te.
. If the verb ends with v or diphthong, the past tense ends in -de.
. If the verb has only one syllable with a long vowel, past tense ends
in -dde.

[cols=",,,",]
|===
|*Rule Number* |*Infinitive* |*Past Tense* |*English*
.2+|*1* |Å vaske |vasket |_Washed_
|Å tegne |tegnet |_Drew_
.2+|*2* |Å besøke |besøkte |_Visited_
|Å kjøre |kjørte |_Drove_
.2+|*3* |Å leve |levde |_Lived_
|Å veie |veide |_Weighed_
.2+|*4* |Å bo |bodde |_Lived_
|Å sy |sydde |_Sewed_
|===

There are two ways to talk about future activities. Sometimes a present
tense verb + a time adverbial is used. Another way to express future
tense is with the use of modal verbs.

[cols=",,",]
|===
| |*Eksempel* |*English*

|*Present Tense + Time Adverbial* |Karina spiser lunsj senere. |_Karina
is eating lunch later._

|*Modal Verbs* |Tobias skal kjøre til biblioteket. |_Tobias is going to
drive to the library._
|===

=== Adjective Basics

Adjectives typically have to agree with the gender and the number of the
noun. If the noun is neuter gender, then in the singular indefinite
form, the adjective takes a *-t ending*. In the plural indefinite, the
adjective takes an *-e ending*. Note there are exceptions.

[cols=",,,,",]
|===
| 2.+|*Singular Indefinite* 2.+|*Plural Indefinite*

| |*Norwegian* |*English* |*Norwegian* |*English*

.2+|*Masculine* |En stor hund |_A big dog_ |Store hunder |_Big dogs_

|En ny film |_A new film_ |Nye filmer |_New films_

.2+|*Feminine* |Ei stor bygning |_A big building_ |Store bygninger |_Big
buildings_

|Ei ny jakke |_A new coat_ |Nye jakker |_New coats_

.2+|*Neuter* |Et stort dyr |_A big animal_ |Store dyr |_Big animals_

|Et nytt leketøy |_A new toy_ |Nye leketøy |_New toys_
|===

When the noun is in the definite form, the adjective takes an *-e*
ending (like in the plural indefinite above).

[cols=",,,,",]
|===
| 2.+|*Singular Definite* 2.+|*Plural Definite*

| |*Norwegian* |*English* |*Norwegian* |*English*

.2+|*Masculine* |Den store hunden |_The big dog_ |De store hundene |_The
big dogs_

|Denne nye filmen |_This new film_ |Disse nye filmene |_These new
films_

.2+|*Feminine* |Den store bygninga |_The big building_ |De store bygningene
|_The big buildings_

|Denne nye jakka |_This new coat_ |Disse nye jakkene |_These new
coats_

.2+|*Neuter* |Det store dyret |_The big animal_ |De store dyra / dyrene
|_The big animals_

|Dette nye leketøyet |_This new toy_ |Disse nye leketøya / leketøyene
|_These new toys_
|===

== Å gjøre
Often translates as “to do” or sometimes as
“to make” and is used in four ways.

{empty}1. The verbal echo - basically this is when it is used
to “echo” a verb that was already used in the sentence.

[cols=",",options="header",]
|===
|*Norwegian* |*English*
|Peter spiser ofte pizza, og det gjør jeg også. |_Peter often eats
pizza, and so do I._

|Tobias kjøpte en ny bok, og det gjorde Sofia også. |_Tobias bought a
new book, and so did Sofia._
|===

In these examples, you can see that “å gjøre” translates to “do” and it
is referring back to “eating pizza” and “bought a new book.”

*[.underline]#NOTE:#* If a modal verb is used in the first part of the
sentence, “gjør” cannot be used. Instead, the modal verb must be used to
“echo.”

*Ex: De vil dra nå, og det _[.underline]#gjør#_ moren min også. -
WRONG!*

*De [.underline]#vil# dra nå, og det _[.underline]#vil#_ moren min også.
- CORRECT!*

They want to leave now, and my mom does also.

{empty}2. In conjunction with an adjective

[cols=",",options="header",]
|===
|*Norwegian* |*English*
|Ole gjorde faren sin sint med løgnene sine. |_Ole made his father angry
with his lies._

|Denne sangen gjør meg glad. |_This song makes me happy._
|===

{empty}3. Finding a solution

[cols=",",options="header",]
|===
|*Norwegian* |*English*
|Hva gjør du når ryggen din klør og armene dine er for korte?! Jeg vet
ikke hva jeg skal gjøre! |_What do you do when your behind itches and
your arms are too short?! I don’t know what to do!_

|Hva skal vi gjøre med klimaendringene? |_What should we do about
climate change?_
|===

{empty}4. Job, occupation, or activity

[cols=",",options="header",]
|===
|*Norwegian* |*English*
|Hva skal du gjøre i helga? |_What are you doing this weekend?_
a|
Person 1: Hva gjør mora di?

Person 2: Hun er (en) bibliotekar.

a|
_Person 1: What does your mom do (for a job)?_

_Person 2: She is a librarian._

|===

*[.underline]#NOTE:#* There are some fixed phrases that use “gjør.”

[cols=",,,",options="header",]
|===
|*Norwegian* |*English* |*Eksempel* |*English*
|Å gjøre en forskjell |_To make a difference_ |Hvis du vil gjøre en
forskjell, bør du resirkulere. |_If you want to make a difference, you
should recycle._

|Å gjøre motstand |_To resist / oppose_ |De gjør motstand mot disse
undertrykkende lovene. |_They oppose these oppressive laws._

|Å gjøre narr av |_To make a fun of / make a fool of_ |Presidenten gjør
ofte narr av personalet sitt. |_The president often makes fun of his
staff._

|Å gjøre skade |_To harm / damage_ |Asteroiden vil gjør skade på
planeten. |_The asteroid will do damage to the planet._

|Det gjør ikke noe |_It does not matter_ |Det gjør ikke noe at du kommer
sent. |_It doesn’t matter if you arrive late._
|===

== Å lage

“Å lage” is used when referring to producing, making, or completing
something.

[cols=",",options="header",]
|===
|*Norwegian* |*English*
|Jeg lager middag hver dag. |_I make dinner every day._

|Barnet laget en kopp til foreldrene sine. |_The child made a cup for
his parents._
|===

Unlike in English, though, “make” cannot be used in more abstract
sentences, like we do in English.

*Ex: å lage et unntak - WRONG!*

*å gjøre et unntak - CORRECT*

To make an exception

== Å Leke vs Å Spille

Both “å leke” and “å spille” mean “to play” (and both can be used as a
noun to mean game: “lek” and “spill”). However they are not
interchangeable.

*_Å leke_* - Used for unstructured playtime, for example playing on a
playground or playing with lego. Additionally, there are some games that
are unstructured but do have structured rules, that also use “å leke.”
It’s also used in unstructured “acting” among children (i.e.
make-believe; playing pretend).

_*Å spille*_ - Used for structured play, usually with a set of rules in
place, such as ball games, board games, video games, etc. “Å spille” is
also used for playing musical instruments and for acting in tv / movies
/ plays. (_*Helpful Hint:*_ _“**S**pille” is ”**S**tructured.”_)

[cols=",,,",options="header",]
|===
| |*Usage* |*Eksempel* |*English*
.4+|*Å leke* .4+|*Unstructured playtime* |Barna leker utenfor. |_The children
are playing outside._

|Moren sa til barna at de skulle leke i parken. |_The mother told
the children to play at the park._

|Anna og Oskar lekte superhelter. |_Anna and Oskar played
superheroes._

|Vi lekte sisten da vi var unge. |_We played tag when we were
young._

.3+|*Å spille* .3+|*Structured play* |Tobias spiller en munnharpe. |_Tobias
plays a mouth harp._

|Markus og Isabella spiller sjakk sammen. |_Markus and Isabella play
/ are playing chess together._

|Mads Mikkelsen spilte regnskapsfører i Rihannas musikkvideo. |_Mads
Mikkelsen played the accountant in Rihanna’s music video._
|===

_**{asterisk}{asterisk}If the lesson was beneficial, please consider
https://ko-fi.com/R5R0CTBN[buying me a virtual coffee.] Thanks.{asterisk}{asterisk}**_

References:

https://www.youtube.com/watch?v=7G8ZEDt7yIQ[Words about
Words: å lage/å gjore (YouTube)]

https://blogs.transparent.com/norwegian/norwegian-verb-to-do/[Norwegian
Verb "To Do"]

https://www.youtube.com/watch?v=oxG915H5X0g&list=PL6RR1L41TROnv1cjfNUkXTiEqf96Ul3S5&index=42[Lær
Norsk! Forskjellen mellom å gjøre og å lage (YouTube på norsk)]

http://www.verbix.com/languages/norwegian.html[Verbix: Verb
Conjugation site]

*[.underline]#Exercise 1:# Fill in the blank answer key (be sure to
conjugate the verbs).*

*COPY & PASTE into a separate document.*

[arabic]
. Liker du å +_____+ kortspill?
. Kattene mine liker å +_____+ med strengen.
. Sønnen min +_____+ en keramiskvase i kunstklasse.
. Hva +_____+ du i helgen?
. Jeg +_____+ et kort til vennen min.
. Filmen +_____+ meg trist.
. Emil og Karina +_____+ gjemsel sammen.
. Jacob håper at han kan +_____+ en forskjell i selskapet.
. Han +_____+ fiolin veldig bra.
. Piratene +_____+ et kart av den begravde skatten.
. Clara sykler ofte til jobb og det +_____+ Sofia også.

*Exercise 2: Write 5 sentences using the verbs in today’s lesson*
